# This python script is used to import the Import the implemented Apriori and H-mine algorithms and trigger them using 3 Different datasets.

import Apriori_Algo
import H_Mine_Algo
import time

#Input dataset file names used for Data mining
input_Dataset1 = "Random_Test.txt"
input_Dataset2 = "Market_Basket_Optimisation.txt"
input_Dataset3 = "Chess_data.txt"

#Output file names to be generated by Apriori
output_Dataset1_Apriori = "Random_Test_Apriori_Output.txt"
output_Dataset2_Apriori = "Market_Basket_Optimisation_Apriori_Output.txt"
output_Dataset3_Apriori = "Chess_data_Apriori_Output.txt"

#Output file names to be generated by H-mine
output_Dataset1_H_mine = "Random_Test_H_mine_Output.txt"
output_Dataset2_H_mine = "Market_Basket_Optimisation_H_mine_Output.txt"
output_Dataset3_H_mine = "Chess_data_H_mine_Output.txt"


#This function triggers the algorithms and returns the execution time
def RunAlgo (algorithm, input_file, output_file, min_sup):
    
    start_time = time.time()   #noting the starting time before calling algorithm

    if algorithm == "Apriori":
        Apriori_Algo.runApriori(input_file, output_file, min_sup)
    
    elif algorithm == "Hmine":
        H_Mine_Algo.runHmine(input_file, output_file, min_sup)
    
    else:
        print("Enter Apriori or Hmine")
    
    end_time = time.time()      #noting the ending time after completion of algorithm

    execution_time = round((end_time - start_time),4)
    
    return execution_time

#This function prints execution time
def print_time(t):
    print("Total run time of algorithm is :",t, "seconds\n")

#Setting below times as 
execution_time = [None] * 6

#Calling Apriori and Hmine algorithms for the 3 datasets given above
execution_time[0] = RunAlgo("Apriori", input_Dataset1, output_Dataset1_Apriori, 0.1)
print_time(execution_time[0])

execution_time[1] = RunAlgo("Apriori", input_Dataset2, output_Dataset2_Apriori, 0.2)
print_time(execution_time[1])

#Apriori Algorithm takes significantly longer run time to complete execution for Chess data. Hence not triggering Apriori algorithm for this Chess_data dataset
# execution_time[2] = RunAlgo("Apriori", input_Dataset3, output_Dataset3_Apriori, 0.95)    
# print_time(execution_time[2])

execution_time[3] = RunAlgo("Hmine", input_Dataset1, output_Dataset1_H_mine, 0.1)
print_time(execution_time[3])

execution_time[4] = RunAlgo("Hmine", input_Dataset2, output_Dataset2_H_mine, 0.2)
print_time(execution_time[4])

execution_time[5] = RunAlgo("Hmine", input_Dataset3, output_Dataset3_H_mine, 0.95)  #H-mine algorithm takes lesser time to generate 
print_time(execution_time[5])


print("*"*20,"Data Mining Completed","*"*20)